name: infrastructure
run-name: deploy infrastructure
on: workflow_dispatch

jobs:
  plan:
    uses: ./.github/workflows/terraform.yml
    with:
      command: plan
    secrets: inherit
  apply:
    uses: ./.github/workflows/terraform.yml
    needs: [plan]
    with:
      command: apply
      options: -auto-approve
    secrets: inherit