name: terraform
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: choice
        options:
          - plan
          - apply
      options:
        required: false
        type: string
        default: ''
      environment:
        required: false
        type: string
        default: ''

jobs:
  terraform:
    name: terraform ${{ inputs.command }}
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.2"
      - run: terraform init
        workdir: Infrastructure
      - run: terraform ${{ inputs.command }} ${{ inputs.options }} -lock=false -state=${{ secrets.TF_STATE }} -var="kube_config_file=${{ secrets.KUBE_CONFIG_FILE }}" -var="kube_config_context=${{ secrets.KUBE_CONFIG_CONTEXT }}"
        workdir: Infrastructure
